<a href="https://colab.research.google.com/github/afif-af/ML/blob/main/advanceLearningAlgorithmWeek02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU
from tensorflow.keras.activations import linear,relu,sigmoid


In [3]:
from sklearn.datasets import make_blobs

In [4]:
def my_softmax(z):
  ez=np.exp(z)
  sm=ez/np.sum(ez)
  return (sm)

In [16]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
x_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [18]:
model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    x_train,y_train,
    epochs=10
)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.3040
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4819
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1966
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1069
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0751
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0621
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0452
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0384
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0410
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0385


In [19]:
p_nonpreferred=model.predict(x_train)
print(p_nonpreferred[0:5])
print("largest value",np.max(p_nonpreferred),
      "min",np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step  
[[7.5528596e-04 1.9792758e-03 9.7888613e-01 1.8379232e-02]
 [9.9610412e-01 3.6382412e-03 1.2697848e-04 1.3064341e-04]
 [9.6786624e-01 2.9430440e-02 1.4518789e-03 1.2512864e-03]
 [2.1162950e-03 9.8660964e-01 6.1700810e-03 5.1039397e-03]
 [1.1410363e-03 2.5114053e-04 9.9839193e-01 2.1585306e-04]]
largest value 0.99999946 min 1.0796354e-08


In [23]:
preferred_model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')    # < softmax activation here
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    x_train,y_train,
    epochs=10
)



Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.4723
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5160
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2035
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1148
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0790
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0692
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0539
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0506
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0525
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0557


In [24]:
p_nonpreferred=model.predict(x_train)
print(p_nonpreferred[0:5])
print("largest value",np.max(p_nonpreferred),
      "min",np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[ -2.59882     -2.0400476    4.9005938   -1.8949064 ]
 [  8.402769     0.92688847  -6.9370933  -10.45173   ]
 [  5.792689     1.8356473   -4.886565    -8.344042  ]
 [ -1.5184112    6.209114    -0.14897972  -3.2485294 ]
 [  0.12741855  -3.705201     6.4650245   -6.6885376 ]]
largest value 16.759354 min -18.20103


In [30]:
p_preferred=preferred_model.predict(x_train)
print(p_preferred[0:5])
print("largest value",np.max(p_preferred),
      "min",np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[-3.706493  -3.116155   2.1937237 -1.1345963]
 [ 6.3514104  1.1408439 -2.8435416 -6.3762455]
 [ 4.4423356  1.2198068 -2.2962239 -5.2041135]
 [-1.8646388  3.1137712 -2.2279313 -3.6494904]
 [-1.149863  -5.923477   4.3318605 -5.855166 ]]
largest value 12.971794 min -9.916341


In [31]:

sm_preferred=tf.nn.softmax(p_preferred).numpy()
print(sm_preferred[0:5])
print("largest value",np.max(sm_preferred),
      "min",np.min(sm_preferred))

[[2.62459111e-03 4.73633362e-03 9.58281577e-01 3.43575478e-02]
 [9.94467616e-01 5.42838126e-03 1.00988924e-04 2.95148220e-06]
 [9.60519612e-01 3.82806845e-02 1.13759306e-03 6.21021463e-05]
 [6.79779891e-03 9.87334192e-01 4.72707255e-03 1.14081940e-03]
 [4.14459640e-03 3.50209593e-05 9.95782793e-01 3.74968695e-05]]
largest value 0.99999696 min 2.2097907e-10


In [32]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-3.706493  -3.116155   2.1937237 -1.1345963], category: 2
[ 6.3514104  1.1408439 -2.8435416 -6.3762455], category: 0
[ 4.4423356  1.2198068 -2.2962239 -5.2041135], category: 0
[-1.8646388  3.1137712 -2.2279313 -3.6494904], category: 1
[-1.149863  -5.923477   4.3318605 -5.855166 ], category: 2


In [38]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                     │ (None, 25)                  │              75 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_31 (Dense)                     │ (None, 15)                  │             390 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_32 (Dense)                     │ (None, 4)                   │              64 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,589 (6.21 KB)

 Trainable params: 529 (2.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,060 (4.14 KB)

# C2_W2

In [34]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [36]:
classes = 4
m = 100
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
std = 1.0
X_train, y_train = make_blobs(n_samples=m, centers=centers, cluster_std=std,random_state=30)