<a href="https://colab.research.google.com/github/afif-af/ML/blob/main/pythonForDataAnalysis01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Alhamdurillah")

Alhamdurillah


In [ ]:
import numpy as np
my_arr=np.arange(1000000)
my_list=list(range(1000000))


In [ ]:
%timeit my_arr2=my_arr *2


2.21 ms ± 550 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit my_list2=my_list *2

23.8 ms ± 9.41 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
import numpy as np

In [ ]:
data=np.array([[1.2,-0.9,3],[3,4,6]])

In [ ]:
data

array([[ 1.2, -0.9,  3. ],
       [ 3. ,  4. ,  6. ]])

In [ ]:
data *10

array([[12., -9., 30.],
       [30., 40., 60.]])

In [ ]:
data+data

array([[ 2.4, -1.8,  6. ],
       [ 6. ,  8. , 12. ]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data1=[6,6.3,7,78,4,3]

In [ ]:
arr1=np.array(data1)

In [ ]:
arr1

array([ 6. ,  6.3,  7. , 78. ,  4. ,  3. ])

In [ ]:
data2=[[1,2,3,4,5],[3,3,545,66,5]]

In [ ]:
arr2=np.array(data2)

In [ ]:
arr2

array([[  1,   2,   3,   4,   5],
       [  3,   3, 545,  66,   5]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 5)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2,3,2))

array([[[6.82183619e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
float_arr=arr.astype(np.float64)

In [ ]:
float_arr

array([1., 2., 3., 4., 5.])

In [ ]:
float_arr.dtype

dtype('float64')

In [ ]:
arr=np.array([3.7,-1.2,-2.6,0.5, 12.9, 10.1])

In [ ]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_strings=np.array(["1.25", "-9.6", "42"],dtype=np.string_)

In [ ]:
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array=np.arange(10)

In [ ]:
calibers=np.array([.22,.270,.357, .380, .44, .50],dtype=np.float64)

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
zeros_uint32=np.zeros(8,dtype="u4")

In [ ]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [ ]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [ ]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr *arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [ ]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
arr=np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8]=12

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice=arr[5:8]

In [ ]:
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1]=12345

In [ ]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:]=64

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]

3

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
old_values=arr3d[0].copy()

In [ ]:
arr3d[0]=42

In [ ]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0]=old_values

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[1,0]

array([7, 8, 9])

In [ ]:
x=arr3d[1]

In [ ]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x[0]

array([7, 8, 9])

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
lower_dim_slice=arr2d[1,:2]

In [ ]:
lower_dim_slice.shape

(2,)

In [ ]:
arr2d[:2,2]

array([3, 6])

In [ ]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2,1:]=0

In [ ]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
names=np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [ ]:
data=np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [ ]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [ ]:
data[names == "Bob", 1]

array([7, 0])

In [ ]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
~(names=="Bob")

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[~(names=="Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
cond = names =="Bob"

In [ ]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
mask = (names == "Bob") | (names == "Will")

In [ ]:
mask

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [ ]:
data[data<0]=0

In [ ]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [ ]:
data[names!="Joe"]=7

In [ ]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [ ]:
arr=np.zeros((8,4))

In [ ]:
for i in range(8):
    arr[i]=i

In [ ]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr=np.arange(32).reshape((8,4))

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [ ]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [ ]:
arr[[1,5,7,2],[0,3,1,2]]=0

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [ ]:
arr=np.arange(15).reshape((3,5))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr=np.array([[0,1,0],[1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])

In [ ]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
arr.T@arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [ ]:
samples=np.random.standard_normal(size=(4,4))

In [ ]:
samples

array([[ 0.75963648,  1.15875989, -0.39966363, -0.24078968],
       [-0.46095736,  0.30021649, -0.67971067,  0.35035345],
       [ 0.75594117, -0.81903092,  0.43917606,  0.9873227 ],
       [-1.68155816,  1.62378902,  2.34101241,  0.31268906]])

In [ ]:
from random import normalvariate

In [ ]:
N=1000000

In [ ]:
%timeit samples=[normalvariate(0,1) for _ in range(N)]

924 ms ± 279 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np.random.standard_normal(N)

29 ms ± 413 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
rng=np.random.default_rng(seed=12345)

In [ ]:
data=rng.standard_normal((2,3))

In [ ]:
arr=np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
x=rng.standard_normal(8)

In [ ]:
y=rng.standard_normal(8)

In [ ]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [ ]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [ ]:
np.maximum(x,y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [ ]:
arr = rng.standard_normal((7)) * 5

In [ ]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [ ]:
remainder, whole_part=np.modf(arr)

In [ ]:
remainder

array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
       -0.40843795,  0.62369966])

In [ ]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [ ]:
out=np.zeros_like(arr)

In [ ]:
np.add(arr, 1)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [ ]:
np.add(arr, 1, out=out)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [ ]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])